name: Death_Logger
version: '${project.version}'
main: me.joshdev.deathlogger.DeathLogger
api-version: 1.19

commands:
  showdeaths:
    description: Retrieve all of your death locations.
    usage: /<command>
    permission: deathlogger.showdeaths
